### ISSUE TITLE
[BUG] atempting to editing metadata causes the app to restart

### ISSUE THREAD

**Issue by TheSilencedOne** [HardcodeCoder/PulseMusic#119]
**Describe the bug**

When i try to edit metadata for a song it it causes the app to restart,

For some reason the app cloned the songs that i tryed to edit the metadata, they cloned to a folder called "working" path:
/Android/data/com.hardcodecoder.pulsemusic/files/working/

**Device and Version Info (please complete the following information):**
 - Device: [Amazon Fire 8 2018]
 - OS: [FireOS 6.3.1.5]
 - Android Version [7.1.2]
 - App Version [4.2.0]

**Additional context**
Add any other context about the problem here

**Logs**
Attach any logs found here: 
[IO_logcat.txt](https://github.com/HardcodeCoder/PulseMusic/files/6489272/IO_logcat.txt)

(im not sure if these are related to this issue)
[GENERAL_logcat.txt](https://github.com/HardcodeCoder/PulseMusic/files/6489275/GENERAL_logcat.txt)
[INFO_logcat.txt](https://github.com/HardcodeCoder/PulseMusic/files/6489276/INFO_logcat.txt)

**Comment by HardcodeCoder** [comment]
This has been fixed 4630ccbebcf29262eaf15467b3a0ebe7a5efbfb1.

**Comment by TheSilencedOne** [comment]
> This has been fixed [4630ccb](https://github.com/HardcodeCoder/PulseMusic/commit/4630ccbebcf29262eaf15467b3a0ebe7a5efbfb1).

@HardcodeCoder im still having the same issue i tryed m4a, mp3, webm, it still cause a restart and still clones the files to that "working" folder heres another log (might be the same one as before)
[IO_logcat.txt](https://github.com/HardcodeCoder/PulseMusic/files/6489538/IO_logcat.txt)

**Comment by HardcodeCoder** [comment]
The "cloning" part is not a bug, its a safety measure to ensure we update the original file only when we have successfully updated tags. Since you are experiencing crash, the app is not able to clean that up. And yes, looks like its not completel fixed

**Comment by HardcodeCoder** [comment]
@TheSilencedOne Just to confirm you are on V4.2.1?

**Comment by TheSilencedOne** [comment]
> @TheSilencedOne Just to confirm you are on V4.2.1?

Yes i am on V4.2.1
